### ISSUE TITLE
MacOS HomeBrew issue

### ISSUE THREAD

**Issue by anim070** [michaeleisel/homebrew-zld#10]
misc/checks.rb
/opt/homebrew/opt/cmake/bin/cmake
xcodebuild -project ld/zld.xcodeproj -scheme zld -derivedDataPath build -configuration Release build ONLY_ACTIVE_ARCH=YES
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
make: *** [build_homebrew] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/michaeleisel/homebrew-zld/issues

**Comment by michaeleisel** [comment]
Xcode.app is required

**Comment by DerekCrosson** [comment]
> Xcode.app is required

@michaeleisel once zld is installed can Xcode be deleted again?
