### ISSUE TITLE
Installation Failures

### ISSUE THREAD

**Issue by Voxelot** [michaeleisel/homebrew-zld#11]
I keep getting http errors when trying to install. I'm on an M1 mac.

```
brew install michaeleisel/zld/zld


==> Downloading https://github.com/michaeleisel/zld/archive/refs/heads/homebrew-fixes-1.3.3.zip
Already downloaded: /Users/voxelot/Library/Caches/Homebrew/downloads/fe560f9185d8fdf96707287aa78ff219507f3143158e1c208848dc1f86503952--zld-homebrew-fixes-1.3.3.zip
==> Installing zld from michaeleisel/zld
==> make clean
==> make build_homebrew
Last 15 lines from /Users/voxelot/Library/Logs/Homebrew/zld/02.make:
missing header for unified diff at line 15 of patch
patching file include/mach-o/dyld_priv.h
Hunk #1 succeeded at 120 (offset -60 lines).
############################################################################################################################################################################################# 100.0%
##########################################6.1%##########################                                                                                                                           3############################################                                                                                                                                                   23.6%################################################                                                                                                                                               25.5%curl: (92) HTTP/2 stream 1 was not closed cleanly before end of the underlying stream

cfe-8.0.1.src/include/clang-c/Index.h: Lzma library error:  No progress is possible
tar: Error exit delayed from previous errors.
make: *** [cfe-8.0.1.src] Error 1
make: *** Waiting for unfinished jobs....
##################################################                                                                                                                                             26.9%curl: (92) HTTP/2 stream 1 was not closed cleanly before end of the underlying stream

llvm-8.0.1.src/lib/Target/AArch64/AArch64PreLegalizerCombiner.cpp: Lzma library error:  No progress is possible
tar: Error exit delayed from previous errors.
make: *** [llvm-8.0.1.src] Error 1

```

**Comment by terryo-iotandwearablesguy** [comment]
Same issue


$brew install michaeleisel/zld/zld
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/core, homebrew/cask and powershell/tap).
==> New Formulae
git-workspace                                                                        pget
==> Updated Formulae
Updated 51 formulae.
==> New Casks
electrum-grs                                                                         ktalk
==> Updated Casks
Updated 28 casks.
==> Deleted Casks
jbidwatcher                                                                          tonido

==> Tapping michaeleisel/zld
Cloning into '/usr/local/Homebrew/Library/Taps/michaeleisel/homebrew-zld'...
remote: Enumerating objects: 98, done.
remote: Counting objects: 100% (98/98), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 98 (delta 21), reused 92 (delta 20), pack-reused 0
Receiving objects: 100% (98/98), 11.78 KiB | 2.95 MiB/s, done.
Resolving deltas: 100% (21/21), done.
Tapped 1 formula (13 files, 19.5KB).
==> Downloading https://ghcr.io/v2/homebrew/core/cmake/manifests/3.23.1_1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/cmake/blobs/sha256:a6a698747b627db43349e0bccf4cbd63c65a18bfabb552dce7ecbde4d3d32962
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:a6a698747b627db43349e0bccf4cbd63c65a18bfabb552dce7ecbde4d3d32962?se=2022-05-20T10%3A
######################################################################## 100.0%
==> Downloading https://github.com/michaeleisel/zld/archive/refs/heads/homebrew-fixes-1.3.3.zip
==> Downloading from https://codeload.github.com/michaeleisel/zld/zip/refs/heads/homebrew-fixes-1.3.3
                 -=O=-                                 #     #   #   #        
==> Installing zld from michaeleisel/zld
==> Installing dependencies for michaeleisel/zld/zld: cmake
==> Installing michaeleisel/zld/zld dependency: cmake
==> Pouring cmake--3.23.1_1.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/cmake/3.23.1_1: 3,043 files, 44.9MB
==> Installing michaeleisel/zld/zld
==> make clean
==> make build_homebrew
Last 15 lines from /Users/terranceoshea/Library/Logs/Homebrew/zld/02.make:
patch -p1 -d dyld-733.6 < patches/dyld.patch
patching file include/mach-o/dyld.h
Hunk #1 succeeded at 150 (offset 6 lines).
missing header for unified diff at line 15 of patch
patching file include/mach-o/dyld_priv.h
Hunk #1 succeeded at 120 (offset -60 lines).
################################################################################################################################################################## 100.0%
############## 27.9%#################################################################################################################################################### 100.0%
######################                                                                                                                                                   ################################################             ###########                                                                                                 #########################                                   ###                         #           #                 #                ########                          ####################################### ############                                #########################     #       #      ##########                              ##########################                    ########## # 16.7#################%############                                                                            ##################  #######        ##########                        ####                        #######                                                                 #####################################      ##########           ###########                                          #############                    ########################                #####             ########          ###  21.7%#############################################################                                         ##############               #######                     #                                          ###########################                                          ################################################################################################## ###                                                                   ###################################################   ###########         ##       #######    ######                                          ###                        ######################################     ##############    ##############           #        ########        ############################                              ########################              #############       #####                   #######             ####                         #########         ############        ##########################################################    #########                  #   ############################                                                ############################################################################################################################### ############                             ###     78.1%################################################                                                                                                            ##########################################################################################                                       #######################   #######       ###########################################################################################                #######  #######             #####      81.5%                  ####                   #######################################################################                                               ##########################################################################                                                                    ###############          #################            ####                       ##################     ##   ######################################                                             ############# ####             ######################################################################            ###    ###############   #######################             ############################################################################################################################################################################################ 100.0%
################################################################################################################################################################## 100.0%
misc/checks.rb
/usr/local/opt/cmake/bin/cmake
xcodebuild -project ld/zld.xcodeproj -scheme zld -derivedDataPath build -configuration Release build ONLY_ACTIVE_ARCH=YES
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
make: *** [build_homebrew] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/michaeleisel/homebrew-zld/issues

$

**Comment by michaeleisel** [comment]
You need to have Xcode installed for this. Or, try downloading the latest release (I will be releasing in the hour), which does not require it

**Comment by melkir** [comment]
For those wondering how to manually download the latest release while waiting for this repo to be updated.
Here's what I've used on my side

1. Download the latest version from https://github.com/michaeleisel/zld/releases and unzip the file.
2. Copy the executable into `/opt/homebrew/bin/`

Or use the following commands:
```
wget -qO- https://github.com/michaeleisel/zld/releases/download/1.3.4/zld.zip | bsdtar -xvf- -C /opt/homebrew/bin/
chmod +x /opt/homebrew/bin/zld
```

**Comment by michaeleisel** [comment]
It's been upgraded

**Comment by melkir** [comment]
Thanks @michaeleisel for keeping us updated on this matter.
On my side I still have the following error
```
❯ brew install zld
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
Running `brew update --auto-update`...

==> Downloading https://github.com/michaeleisel/zld/archive/709187361b9871984eaf92057c74cc4aa4a4906f.zip
Already downloaded: /Users/thibaultvieux/Library/Caches/Homebrew/downloads/328f1bc7a9d146e93da3220cd2711fcb2588882dff94fb642e3984e0e7a8b65d--zld-709187361b9871984eaf92057c74cc4aa4a4906f.zip
==> Installing zld from michaeleisel/zld
==> make clean
==> make build_homebrew
Last 15 lines from /Users/thibaultvieux/Library/Logs/Homebrew/zld/02.make:
############################################################################################################ 100.0%
#########################################                                                                     38.6%patch -p1 -d tapi-1100.0.11 < patches/tapi.patch
patching file include/tapi/Version.inc
############################################################################################################ 100.0%
#####                                                                                                          5.5%#########                                                                                                      8.7%Updating files: 100% (1560/1560), done.
patch -p1 -d dyld-940 < patches/dyld.patch
patching file include/mach-o/dyld.h
patching file include/mach-o/dyld_priv.h
Hunk #1 succeeded at 130 (offset 4 lines).
############################################################################################################ 100.0%
misc/checks.rb
/opt/homebrew/opt/cmake/bin/cmake
xcodebuild -project ld/zld.xcodeproj -scheme zld -derivedDataPath build -configuration Release build ONLY_ACTIVE_ARCH=YES
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
make: *** [build_homebrew] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/michaeleisel/homebrew-zld/issues
```

**Comment by melkir** [comment]
Thanks @michaeleisel for keeping us updated on this matter.
On my side I still have the following error
```
❯ brew install zld
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
Running `brew update --auto-update`...

==> Downloading https://github.com/michaeleisel/zld/archive/709187361b9871984eaf92057c74cc4aa4a4906f.zip
Already downloaded: /Users/thibaultvieux/Library/Caches/Homebrew/downloads/328f1bc7a9d146e93da3220cd2711fcb2588882dff94fb642e3984e0e7a8b65d--zld-709187361b9871984eaf92057c74cc4aa4a4906f.zip
==> Installing zld from michaeleisel/zld
==> make clean
==> make build_homebrew
Last 15 lines from /Users/melkir/Library/Logs/Homebrew/zld/02.make:
############################################################################################################ 100.0%
#########################################                                                                     38.6%patch -p1 -d tapi-1100.0.11 < patches/tapi.patch
patching file include/tapi/Version.inc
############################################################################################################ 100.0%
#####                                                                                                          5.5%#########                                                                                                      8.7%Updating files: 100% (1560/1560), done.
patch -p1 -d dyld-940 < patches/dyld.patch
patching file include/mach-o/dyld.h
patching file include/mach-o/dyld_priv.h
Hunk #1 succeeded at 130 (offset 4 lines).
############################################################################################################ 100.0%
misc/checks.rb
/opt/homebrew/opt/cmake/bin/cmake
xcodebuild -project ld/zld.xcodeproj -scheme zld -derivedDataPath build -configuration Release build ONLY_ACTIVE_ARCH=YES
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
make: *** [build_homebrew] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/michaeleisel/homebrew-zld/issues
```

**Comment by melkir** [comment]
Thanks @michaeleisel for keeping us updated on this matter.
On my side I still have the following error
```
❯ brew install zld
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
Running `brew update --auto-update`...

==> Downloading https://github.com/michaeleisel/zld/archive/709187361b9871984eaf92057c74cc4aa4a4906f.zip
Already downloaded: /Users/melkir/Library/Caches/Homebrew/downloads/328f1bc7a9d146e93da3220cd2711fcb2588882dff94fb642e3984e0e7a8b65d--zld-709187361b9871984eaf92057c74cc4aa4a4906f.zip
==> Installing zld from michaeleisel/zld
==> make clean
==> make build_homebrew
Last 15 lines from /Users/melkir/Library/Logs/Homebrew/zld/02.make:
############################################################################################################ 100.0%
#########################################                                                                     38.6%patch -p1 -d tapi-1100.0.11 < patches/tapi.patch
patching file include/tapi/Version.inc
############################################################################################################ 100.0%
#####                                                                                                          5.5%#########                                                                                                      8.7%Updating files: 100% (1560/1560), done.
patch -p1 -d dyld-940 < patches/dyld.patch
patching file include/mach-o/dyld.h
patching file include/mach-o/dyld_priv.h
Hunk #1 succeeded at 130 (offset 4 lines).
############################################################################################################ 100.0%
misc/checks.rb
/opt/homebrew/opt/cmake/bin/cmake
xcodebuild -project ld/zld.xcodeproj -scheme zld -derivedDataPath build -configuration Release build ONLY_ACTIVE_ARCH=YES
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
make: *** [build_homebrew] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/michaeleisel/homebrew-zld/issues
```

**Comment by michaeleisel** [comment]
Ah right, my mistake. The new release is _runnable_ without Xcode, but not _buildable_ without Xcode. Anyways, while I have some people in this GH issue, have any of you tried lld? It has become quite stable recently is generally much faster.

**Comment by melkir** [comment]
I don't think LLD is available on macOS at the moment. At least that what's the doc from [Bevy](https://bevyengine.org/learn/book/getting-started/setup/#enable-fast-compiles-optional) says.
At the moment I didn't see any real difference between the default configuration and the optimization with zld but their codes samples might not be representative at all 🤓
